apiVersion: v1
kind: Secret
metadata:
  name: apim-local-secure-vault
type: Opaque
stringData:
  masterEncryptionKey: "7edc2878ee5921997b436ff6e615540783e86c52cb2bb322bb96e6fcc371e58d"
  internalKeystorePassword: "wso2carbon"
